apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kotlin-guestbook
  template:
    metadata:
      labels:
        app: kotlin-guestbook
    spec:
      containers:
      - name: kotlin-guestbook
        image: docker.io/waveywaves/mirrord-kotlin-example:v6
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"